// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitBot() (*Bot, error) {
	config := fromEnv()
	botAPI, err := newTgBot(config)
	if err != nil {
		return nil, err
	}
	updatesChannel, err := getUpdatesChan(config, botAPI)
	if err != nil {
		return nil, err
	}
	bot := NewBot(botAPI, updatesChannel)
	return bot, nil
}
